import {
  Organization,
  Client,
  Transaction,
  Statistics,
  ChartDataPoint,
  User,
  Invoice,
} from './types';

export const mockOrganizations: Organization[] = [
  {
    id: '1',
    name: 'TechVision Inc',
    type: 'Business',
    logo: '🏢',
    members: 24,
    activePlan: 'Enterprise',
    status: 'Active',
    createdDate: '2023-01-15',
    revenue: 125000,
  },
  {
    id: '2',
    name: 'Digital Solutions Ltd',
    type: 'Business',
    logo: '💼',
    members: 18,
    activePlan: 'Professional',
    status: 'Active',
    createdDate: '2023-03-22',
    revenue: 89500,
  },
  {
    id: '3',
    name: 'StartupHub',
    type: 'Startup',
    logo: '🚀',
    members: 12,
    activePlan: 'Professional',
    status: 'Active',
    createdDate: '2023-06-10',
    revenue: 45000,
  },
  {
    id: '4',
    name: 'CloudNet Systems',
    type: 'Enterprise',
    logo: '☁️',
    members: 45,
    activePlan: 'Enterprise',
    status: 'Active',
    createdDate: '2022-11-05',
    revenue: 250000,
  },
  {
    id: '5',
    name: 'Design Studios Co',
    type: 'Business',
    logo: '🎨',
    members: 8,
    activePlan: 'Starter',
    status: 'Active',
    createdDate: '2024-01-20',
    revenue: 32000,
  },
];

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    organizationId: '1',
    email: 'alex@example.com',
    phone: '+1-555-0101',
    package: 'Premium',
    paymentStatus: 'Paid',
    renewalDate: '2024-12-15',
    totalSpent: 15500,
    totalProducts: 12,
    status: 'Active',
    lastActivity: '2024-06-28',
    totalCustomers: 8,
    notes: 'VIP client, high priority support',
    companyName: 'Johnson Enterprises',
    joinDate: '2023-02-01',
  },
  {
    id: '2',
    name: 'Sarah Mitchell',
    organizationId: '1',
    email: 'sarah@example.com',
    phone: '+1-555-0102',
    package: 'Standard',
    paymentStatus: 'Pending',
    renewalDate: '2024-11-20',
    totalSpent: 8900,
    totalProducts: 7,
    status: 'Active',
    lastActivity: '2024-06-25',
    totalCustomers: 5,
    notes: 'Regular client, good payment history',
    companyName: 'Mitchell & Co',
    joinDate: '2023-05-15',
  },
  {
    id: '3',
    name: 'Michael Chen',
    organizationId: '2',
    email: 'michael@example.com',
    phone: '+1-555-0103',
    package: 'Premium',
    paymentStatus: 'Paid',
    renewalDate: '2024-10-30',
    totalSpent: 22000,
    totalProducts: 15,
    status: 'Active',
    lastActivity: '2024-06-27',
    totalCustomers: 12,
    notes: 'Enterprise client, custom integrations',
    companyName: 'Chen Solutions',
    joinDate: '2022-11-20',
  },
  {
    id: '4',
    name: 'Emily Davis',
    organizationId: '3',
    email: 'emily@example.com',
    phone: '+1-555-0104',
    package: 'Basic',
    paymentStatus: 'Overdue',
    renewalDate: '2024-09-15',
    totalSpent: 5400,
    totalProducts: 4,
    status: 'Suspended',
    lastActivity: '2024-06-10',
    totalCustomers: 3,
    notes: 'Payment issue needs attention',
    companyName: 'Davis Consulting',
    joinDate: '2023-08-30',
  },
  {
    id: '5',
    name: 'James Wilson',
    organizationId: '2',
    email: 'james@example.com',
    phone: '+1-555-0105',
    package: 'Premium',
    paymentStatus: 'Paid',
    renewalDate: '2024-12-01',
    totalSpent: 18900,
    totalProducts: 10,
    status: 'Active',
    lastActivity: '2024-06-28',
    totalCustomers: 9,
    notes: 'Loyal customer, expansion potential',
    companyName: 'Wilson Group',
    joinDate: '2023-03-10',
  },
  {
    id: '6',
    name: 'Lisa Anderson',
    organizationId: '1',
    email: 'lisa@example.com',
    phone: '+1-555-0106',
    package: 'Standard',
    paymentStatus: 'Paid',
    renewalDate: '2024-11-10',
    totalSpent: 11200,
    totalProducts: 8,
    status: 'Active',
    lastActivity: '2024-06-26',
    totalCustomers: 6,
    notes: 'Consistent growth, quarterly reviews',
    companyName: 'Anderson Tech',
    joinDate: '2023-06-01',
  },
  {
    id: '7',
    name: 'Robert Brown',
    organizationId: '2',
    email: 'robert@example.com',
    phone: '+1-555-0107',
    package: 'Basic',
    paymentStatus: 'Paid',
    renewalDate: '2024-10-15',
    totalSpent: 6800,
    totalProducts: 5,
    status: 'Active',
    lastActivity: '2024-06-24',
    totalCustomers: 4,
    notes: 'New client, onboarding complete',
    companyName: 'Brown Industries',
    joinDate: '2024-01-15',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    invoiceNumber: 'INV-2024-001',
    clientId: '1',
    organizationId: '1',
    amount: 5500,
    paymentMethod: 'Credit Card',
    date: '2024-06-15',
    status: 'Paid',
    dueDate: '2024-07-15',
  },
  {
    id: '2',
    invoiceNumber: 'INV-2024-002',
    clientId: '2',
    organizationId: '1',
    amount: 3200,
    paymentMethod: 'Bank Transfer',
    date: '2024-06-18',
    status: 'Pending',
    dueDate: '2024-07-18',
  },
  {
    id: '3',
    invoiceNumber: 'INV-2024-003',
    clientId: '3',
    organizationId: '2',
    amount: 8900,
    paymentMethod: 'Credit Card',
    date: '2024-06-10',
    status: 'Paid',
    dueDate: '2024-07-10',
  },
  {
    id: '4',
    invoiceNumber: 'INV-2024-004',
    clientId: '4',
    organizationId: '3',
    amount: 2400,
    paymentMethod: 'PayPal',
    date: '2024-05-20',
    status: 'Overdue',
    dueDate: '2024-06-20',
  },
  {
    id: '5',
    invoiceNumber: 'INV-2024-005',
    clientId: '5',
    organizationId: '2',
    amount: 6200,
    paymentMethod: 'Bank Transfer',
    date: '2024-06-22',
    status: 'Paid',
    dueDate: '2024-07-22',
  },
];

export const mockStatistics: Statistics[] = [
  {
    label: "Today's Income",
    value: '$12,450',
    change: 12.5,
    icon: '📈',
    trend: 'up',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    label: 'Monthly Income',
    value: '$125,890',
    change: 8.3,
    icon: '💰',
    trend: 'up',
    color: 'from-green-500 to-emerald-500',
  },
  {
    label: 'Yearly Income',
    value: '$1,445,230',
    change: 23.8,
    icon: '📊',
    trend: 'up',
    color: 'from-purple-500 to-pink-500',
  },
  {
    label: 'Pending Payments',
    value: '$34,560',
    change: -5.2,
    icon: '⏳',
    trend: 'down',
    color: 'from-orange-500 to-red-500',
  },
];

export const mockChartData: ChartDataPoint[] = [
  { name: 'Jan', revenue: 45000, growth: 5 },
  { name: 'Feb', revenue: 52000, growth: 8 },
  { name: 'Mar', revenue: 48000, growth: 3 },
  { name: 'Apr', revenue: 61000, growth: 12 },
  { name: 'May', revenue: 75000, growth: 18 },
  { name: 'Jun', revenue: 89000, growth: 22 },
  { name: 'Jul', revenue: 95000, growth: 25 },
];

export const mockIncomeDistribution: ChartDataPoint[] = [
  { name: 'TechVision Inc', value: 125000 },
  { name: 'CloudNet Systems', value: 250000 },
  { name: 'Digital Solutions', value: 89500 },
  { name: 'StartupHub', value: 45000 },
  { name: 'Design Studios', value: 32000 },
];

export const mockCurrentUser: User = {
  id: '1',
  name: 'John Smith',
  email: 'john.smith@example.com',
  avatar: '👤',
  role: 'Admin',
};

export const mockInvoices: Invoice[] = [
  {
    id: '1',
    invoiceNumber: 'INV-2024-001',
    date: '2024-06-15',
    dueDate: '2024-07-15',
    client: mockClients[0],
    items: [
      {
        description: 'Professional Services',
        quantity: 10,
        unitPrice: 500,
        amount: 5000,
      },
      {
        description: 'Consultation Fee',
        quantity: 1,
        unitPrice: 300,
        amount: 300,
      },
    ],
    subtotal: 5300,
    tax: 530,
    total: 5830,
    notes: 'Thank you for your business!',
    status: 'Paid',
  },
  {
    id: '2',
    invoiceNumber: 'INV-2024-002',
    date: '2024-06-18',
    dueDate: '2024-07-18',
    client: mockClients[1],
    items: [
      {
        description: 'Monthly Subscription',
        quantity: 1,
        unitPrice: 3000,
        amount: 3000,
      },
    ],
    subtotal: 3000,
    tax: 300,
    total: 3300,
    status: 'Sent',
  },
];
